/**
 * Stores module exports.
 * Re-exports all Svelte stores from a single entry point.
 */

export { user, isSignedIn, type AppUser } from './user';

export {
	gameData,
	gameDataLoading,
	metatypes,
	skills,
	qualities,
	positiveQualities,
	negativeQualities,
	spells,
	powers,
	traditions,
	weapons,
	armor,
	cyberware,
	gear,
	lifestyles,
	loadGameData,
	findMetatype,
	findSkill,
	findQuality,
	findWeapon,
	findArmor,
	findCyberware,
	findGear,
	filterSkillsByCategory,
	filterSkillsByGroup,
	filterWeaponsByCategory,
	filterArmorByCategory,
	filterCyberwareByCategory,
	filterGearByCategory,
	type GameData,
	type GameQuality,
	type GameSpell,
	type GamePower,
	type GameTradition,
	type GameMentor,
	type GameLifestyle,
	type GameProgram,
	type SkillCategoryDef
} from './gamedata';

export {
	character,
	currentStep,
	currentStepIndex,
	remainingBP,
	bpBreakdown,
	hasMetatype,
	magicType,
	remainingNuyen,
	startingNuyen,
	currentEssence,
	isDirty,
	startNewCharacter,
	setWizardStep,
	nextWizardStep,
	prevWizardStep,
	setMetatype,
	setAttribute,
	addQuality,
	removeQuality,
	setSkill,
	removeSkill,
	addContact,
	removeContact,
	updateIdentity,
	initializeMagic,
	setTradition,
	addSpell,
	removeSpell,
	addPower,
	removePower,
	initializeResonance,
	getMagicType,
	setResourcesBP,
	addWeapon,
	removeWeapon,
	addArmor,
	removeArmor,
	addCyberware,
	removeCyberware,
	addGear,
	removeGear,
	setLifestyle,
	removeLifestyle,
	saveCurrentCharacter,
	loadSavedCharacter,
	loadImportedCharacter,
	deleteSavedCharacter,
	listCharacters,
	duplicateCurrentCharacter,
	clearCurrentCharacter,
	markAsSaved,
	hasUnsavedChanges,
	enableAutoSave,
	disableAutoSave,
	/* Career mode */
	KARMA_COSTS,
	isCareerMode,
	enterCareerMode,
	awardKarma,
	awardNuyen,
	spendNuyen,
	getAttributeImprovementCost,
	improveAttribute,
	getSkillImprovementCost,
	improveSkill,
	learnNewSkill,
	addSpecialization,
	learnKnowledgeSkill,
	improveKnowledgeSkill,
	learnSpell,
	getInitiationCost,
	initiate,
	getExpenseLog,
	WIZARD_STEPS,
	type WizardStep,
	type WizardStepConfig,
	type AttributeValueKey,
	type MagicType,
	type CharacterSummary
} from './character';
