/**
 * Stores module exports.
 * Re-exports all Svelte stores from a single entry point.
 */

export { user, isSignedIn, type AppUser } from './user';

export {
	gameData,
	gameDataLoading,
	metatypes,
	skills,
	qualities,
	positiveQualities,
	negativeQualities,
	spells,
	powers,
	traditions,
	mentors,
	programs,
	programCategories,
	weapons,
	armor,
	cyberware,
	gear,
	lifestyles,
	/* Bioware */
	bioware,
	biowareCategories,
	/* Vehicles & Drones */
	vehicles,
	vehicleCategories,
	drones,
	/* Martial Arts */
	martialArts,
	/* Technomancer */
	echoes,
	streams,
	loadGameData,
	findMetatype,
	findSkill,
	findQuality,
	findWeapon,
	findArmor,
	findCyberware,
	findGear,
	findBioware,
	findVehicle,
	findMartialArt,
	findEcho,
	findStream,
	filterSkillsByCategory,
	filterSkillsByGroup,
	filterWeaponsByCategory,
	filterArmorByCategory,
	filterCyberwareByCategory,
	filterGearByCategory,
	filterBiowareByCategory,
	filterVehiclesByCategory,
	type GameData,
	type GameQuality,
	type GameSpell,
	type GamePower,
	type GameTradition,
	type GameMentor,
	type GameLifestyle,
	type GameProgram,
	type GameBioware,
	type GameVehicle,
	type GameMartialArt,
	type GameEcho,
	type GameStream,
	type SkillCategoryDef
} from './gamedata';

export {
	character,
	currentStep,
	currentStepIndex,
	remainingBP,
	bpBreakdown,
	hasMetatype,
	magicType,
	remainingNuyen,
	startingNuyen,
	currentEssence,
	isDirty,
	startNewCharacter,
	setBuildMethod,
	KARMA_BUILD_COSTS,
	setWizardStep,
	nextWizardStep,
	prevWizardStep,
	setMetatype,
	setAttribute,
	addQuality,
	removeQuality,
	setSkill,
	removeSkill,
	addContact,
	removeContact,
	updateIdentity,
	initializeMagic,
	setTradition,
	setMentor,
	addSpell,
	removeSpell,
	addPower,
	removePower,
	initializeResonance,
	addComplexForm,
	removeComplexForm,
	learnComplexForm,
	getMagicType,
	setResourcesBP,
	addWeapon,
	removeWeapon,
	addArmor,
	removeArmor,
	addCyberware,
	removeCyberware,
	/* Bioware */
	addBioware,
	removeBioware,
	/* Vehicles */
	addVehicle,
	removeVehicle,
	/* Martial Arts */
	addMartialArt,
	removeMartialArt,
	addMartialArtTechnique,
	removeMartialArtTechnique,
	MARTIAL_ARTS_COSTS,
	addGear,
	removeGear,
	setLifestyle,
	removeLifestyle,
	saveCurrentCharacter,
	loadSavedCharacter,
	loadImportedCharacter,
	deleteSavedCharacter,
	listCharacters,
	duplicateCurrentCharacter,
	clearCurrentCharacter,
	markAsSaved,
	hasUnsavedChanges,
	enableAutoSave,
	disableAutoSave,
	/* Career mode */
	KARMA_COSTS,
	isCareerMode,
	enterCareerMode,
	awardKarma,
	awardNuyen,
	spendNuyen,
	getAttributeImprovementCost,
	improveAttribute,
	getSkillImprovementCost,
	improveSkill,
	learnNewSkill,
	addSpecialization,
	learnKnowledgeSkill,
	improveKnowledgeSkill,
	learnSpell,
	getInitiationCost,
	initiate,
	/* Technomancer submersion */
	getSubmersionCost,
	submerge,
	learnEcho,
	removeEcho,
	getExpenseLog,
	/* Gameplay tracking */
	updateCondition,
	updateEdge,
	spendAmmo,
	reloadWeapon,
	setAmmo,
	WIZARD_STEPS,
	type WizardStep,
	type WizardStepConfig,
	type AttributeValueKey,
	type MagicType,
	type CharacterSummary
} from './character';
